### ISSUE TITLE
Client should't die when receiving invalid statements

### ISSUE THREAD

**Issue by flowlight0** [flowlight0/simpledb-rs#30]
It was caused by panic at rollback. 
```
Connect> foo
SQL (foo)> s

thread 'main' panicked at src/tx/transaction.rs:305:17:
unexpected log record: Commit(1)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: simpledb_rs::tx::transaction::Transaction::undo_update
             at ./src/tx/transaction.rs:305:17
   3: simpledb_rs::tx::transaction::Transaction::do_rollback
             at ./src/tx/transaction.rs:259:13
   4: simpledb_rs::tx::transaction::Transaction::rollback
             at ./src/tx/transaction.rs:67:9
   5: simpledb_rs::driver::embedded::EmbeddedConnectionImpl::rollback
             at ./src/driver/embedded.rs:148:9
   6: <simpledb_rs::driver::embedded::EmbeddedConnection as simpledb_rs::driver::ConnectionControl>::rollback
             at ./src/driver/embedded.rs:189:12
   7: <simpledb_rs::driver::Connection as simpledb_rs::driver::ConnectionControl>::rollback
             at ./src/driver/mod.rs:64:1
   8: client::main
             at ./src/client.rs:101:13
   9: core::ops::function::FnOnce::call_once
             at /Users/thayashi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```

**Comment by flowlight0** [comment]
The above panic happened because of my transaction ID assignment implementation. The transaction ID restarts from 0 when DB restarts. This makes my rollback implementation scans log records written before the last DB restart. My rollback should stop at CHECKPOINT to avoid scanning transaction with conflicting IDs.
